Lsp clojure
lite-xl/lite-xl-lsp-servers pull request #37
Opened 2024-04-11 09:52 UTC by RohanVashisht1234

I have added lsp clojure

2024-04-11 15:09 UTC, Guldoman requested changes
Also format the manifest please.

2024-04-11 15:09 UTC, Guldoman commented on manifest.json
> +    "version": "2024.03.31-19.10.13",
We don't support dashes in the version.
It's probably fine to just drop the dash and anything after it.

2024-04-11 15:09 UTC, Guldoman commented on manifest.json
> +    ],
```suggestion
    "files": [
      {
        "url": "https://github.com/clojure-lsp/clojure-lsp/releases/download/2024.03.31-19.10.13/clojure-lsp-native-linux-aarch64.zip",
        "arch": "aarch64-linux",
        "checksum": "0715435335d09f03deebbe946275196cac400f3b379dfb0bd55a060fe46d49b4"
      },
      {
        "url": "https://github.com/clojure-lsp/clojure-lsp/releases/download/2024.03.31-19.10.13/clojure-lsp-native-linux-amd64.zip",
        "arch": "x86_64-linux",
        "checksum": "3d860d25e7c354198fa9c975ba01bfb27d1aba42d8e334f0e529bbfdc5c1a5e6"
      },
      {
        "url": "https://github.com/clojure-lsp/clojure-lsp/releases/download/2024.03.31-19.10.13/clojure-lsp-native-macos-aarch64.zip",
        "arch": "aarch64-darwin",
        "checksum": "78ada7b23d604f1542efea29e283baa26f3e9011450929d876827cc148817f62"
      },
      {
        "url": "https://github.com/clojure-lsp/clojure-lsp/releases/download/2024.03.31-19.10.13/clojure-lsp-native-macos-amd64.zip",
        "arch": "x86_64-darwin",
        "checksum": "ec8468a2aef17ee365c0d4f79a069f441c5fe9d466286929af012060dbf68a35"
      },
      {
        "url": "https://github.com/clojure-lsp/clojure-lsp/releases/download/2024.03.31-19.10.13/clojure-lsp-native-windows-amd64.zip",
        "arch": "x86_64-windows",
        "checksum": "c29acff1dc06f5810b055c67722e7109bcc8c80b80f24feac37998a8320930e0"
      }
    ],
```

2024-04-11 15:09 UTC, Guldoman commented on plugins/lsp_clojure.lua
> +}, config.plugins.lsp_rust or {}))
```suggestion
lspconfig.clojure_lsp.setup(common.merge({
  command = { installed_path .. PATHSEP .. filename }
}, config.plugins.lsp_clojure or {}))
```

2024-04-11 15:09 UTC, Guldoman commented on plugins/lsp_clojure.lua
> +end
```suggestion
local filename = "clojure-lsp" .. (PLATFORM == "Windows" and ".exe" or "")
```

2024-04-11 15:47 UTC, RohanVashisht1234 commented
I think I have resolved all the issues

2024-04-11 16:02 UTC, RohanVashisht1234 commented
yes, also I have changed the linux-native to linux-static-native for better compatibility

2024-04-11 16:49 UTC, RohanVashisht1234 commented
ok, everything has been fixed, added a few things also

2024-04-11 18:06 UTC, Guldoman requested changes
It looks like you're changing a lot of unrelated entries in the manifest. Could you revert that?

2024-04-11 18:06 UTC, Guldoman commented on plugins/lsp_clojure.lua
> +  command = { installed_path .. PATHSEP .. filename }
You aren't defining `filename`.

2024-04-11 18:25 UTC, RohanVashisht1234 commented
ok, fixed that also

2024-04-11 18:42 UTC, RohanVashisht1234 commented
Yes, changed the formatting of the json to origionals

2024-04-11 23:10 UTC, Guldoman approved these changes
Looks good!

Tested on Linux and it seems to work fine without any additional dependency.
Can anybody test on Windows and macOS?

2024-04-12 18:46 UTC, RohanVashisht1234 commented
Has been tested to be working perfectly well on macos  aarch 64

https://media.discordapp.net/attachments/847122429742809211/1228412928034734090/rohanvashishtmactesting.mov?ex=662bf3b0&is=66197eb0&hm=d9e966c109fe062089e0e7fed35509015d956e01c5f5ea8132a45fcfa0ee6492&

2024-04-15 17:13 UTC, Guldoman commented
Seems to work fine on Windows too.
Waiting on lite-xl/lite-xl-plugins#421 to be merged.

2024-04-16 17:45 UTC, merged